// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	model "github.com/mespinosago/unitag/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GetURL provides a mock function with given fields: code, options
func (_m *Service) GetURL(code string, options model.Options) (string, error) {
	ret := _m.Called(code, options)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, model.Options) (string, error)); ok {
		return rf(code, options)
	}
	if rf, ok := ret.Get(0).(func(string, model.Options) string); ok {
		r0 = rf(code, options)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, model.Options) error); ok {
		r1 = rf(code, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type Service_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - code string
//   - options model.Options
func (_e *Service_Expecter) GetURL(code interface{}, options interface{}) *Service_GetURL_Call {
	return &Service_GetURL_Call{Call: _e.mock.On("GetURL", code, options)}
}

func (_c *Service_GetURL_Call) Run(run func(code string, options model.Options)) *Service_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.Options))
	})
	return _c
}

func (_c *Service_GetURL_Call) Return(_a0 string, _a1 error) *Service_GetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetURL_Call) RunAndReturn(run func(string, model.Options) (string, error)) *Service_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
